# Generated by Django 4.1.2 on 2022-10-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kelompok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpus_app.kelompok'),
        ),
    ]
