# Generated by Django 4.1.2 on 2022-11-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perpus_app", "0003_buku_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buku", old_name="kelompok_id", new_name="Kelompok",
        ),
    ]
