# Generated by Django 4.1.4 on 2023-01-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0004_rename_kelompok_id_buku_kelompok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koordinat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10000)),
                ('koordinat', models.CharField(max_length=54)),
            ],
        ),
        migrations.AlterField(
            model_name='buku',
            name='penulis',
            field=models.CharField(max_length=100),
        ),
    ]
